//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travelogue
    {
        public int TId { get; set; }
        public string Destination { get; set; }
        public string Details { get; set; }
        public System.DateTime TravelDate { get; set; }
        public int NoOfDays { get; set; }
    }
}
